
version: "3.8"
services:
  agent-swarm:
    build: .
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
